use tourismdb;
INSERT INTO cities (CityName)
VALUES
    ('Copenhagen'),
    ('Herning'),
    ('Aalborg'),
    ('Odense'),
    ('Aarhus'),
    ('Esbjerg'),
    ('Billund'),
    ('Bornholm'),
    ('Helsingør'),
    ('Skagen');

insert into regions(RegionName)
values
    ('Capital Region of Denmark'),
    ('Region Zealand'),
    ('Central Denmark Region'),
    ('Region of Southern Denmark'),
    ('North Denmark Region');

insert into regions (Province)
values
    ('Copenhagen City'),
    ('Copenhagen Surroundings'),
    ('North Zealand'),
    ('East Zealand'),
    ('West & South Zealand'),
    ('Bornholm'),
    ('Funen'),
    ('South Jutland'),
    ('East Jutland'),
    ('West Jutland'),
    ('North Jutland');

insert into cities(Municipality)
values
    ('Copenhagen'),
    ('Aarhus'),
    ('Aalborg'),
    ('Odense'),
    ('Esbjerg'),
    ('Vejle'),
    ('Frederiksberg'),
    ('Randers'),
    ('Viborg'),
    ('Kolding'),
    ('Silkeborg'),
    ('Herning'),
    ('Horsens'),
    ('Roskilde'),
    ('Næstved'),
    ('Slagelse'),
    ('Sønderborg'),
    ('Gentofte'),
    ('Holbæk'),
    ('Hjørring'),
    ('Gladsaxe'),
    ('Guldborgsund'),
    ('Helsingør'),
    ('Frederikshavn'),
    ('Aabenraa'),
    ('Svendborg'),
    ('Skanderborg'),
    ('Ringkøbing-Skjern'),
    ('Køge'),
    ('Holstebro'),
    ('Haderslev'),
    ('Rudersdal'),
    ('Lyngby-Taarbæk'),
    ('Faaborg-Midtfyn'),
    ('Hvidovre'),
    ('Varde'),
    ('Fredericia'),
    ('Kalundborg'),
    ('Hillerød'),
    ('Høje-Taastrup'),
    ('Ballerup'),
    ('Greve'),
    ('Skive'),
    ('Favrskov'),
    ('Hedensted'),
    ('Vordingborg'),
    ('Lolland'),
    ('Thisted'),
    ('Frederikssund'),
    ('Vejen'),
    ('Mariagerfjord'),
    ('Egedal'),
    ('Syddjurs'),
    ('Assens'),
    ('Bornholm'),
    ('Tårnby'),
    ('Ikast-Brande'),
    ('Gribskov'),
    ('Fredensborg'),
    ('Tønder'),
    ('Jammerbugt'),
    ('Furesø'),
    ('Norddjurs'),
    ('Middelfart'),
    ('Vesthimmerland'),
    ('Rødovre'),
    ('Brønderslev'),
    ('Faxe'),
    ('Brøndby'),
    ('Ringsted'),
    ('Odsherred'),
    ('Nyborg'),
    ('Halsnæs'),
    ('Sorø'),
    ('Nordfyn'),
    ('Rebild'),
    ('Albertslund'),
    ('Lejre'),
    ('Herlev'),
    ('Billund'),
    ('Hørsholm'),
    ('Allerød'),
    ('Kerteminde'),
    ('Struer'),
    ('Stevns'),
    ('Odder'),
    ('Glostrup'),
    ('Morsø'),
    ('Lemvig'),
    ('Solrød'),
    ('Ishøj'),
    ('Vallensbæk'),
    ('Dragør'),
    ('Langeland'),
    ('Ærø'),
    ('Samsø'),
    ('Fanø'),
    ('Læsø');


